name: Create DNS Records

on:
  pull_request:
    types: [closed]

jobs:
  create-dns:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Validate JSON Files
      run: |
        for file in subdomains/*.json; do
          echo "Validating $file"
          jq empty $file
        done

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Cloudflare Python package
      run: pip install cloudflare

    - name: Create DNS Records
      env:
        CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      run: |
        python3 .github/scripts/create_dns_records.py
